/*   FILE: Metadata.java
 *   DATE OF CREATION:   Mon Dec 01 10:12:36 2003
 *   AUTHOR :            Emmanuel Pietriga (emmanuel@claribole.net)
 *   MODIF:              Emmanuel Pietriga (emmanuel.pietriga@inria.fr)
 *   Copyright (c) Emmanuel Pietriga, 2003. All Rights Reserved
 *   Licensed under the GNU LGPL. For full terms see the file COPYING.
 */

package com.xerox.VTM.svg;

/**metadata information attached to SVG graphical elements (title, URL, ...) - attached to glyphs generated by SVGReader (use Glyph.getOwner() to retrieve this information)*/

public class Metadata {

    String url;
    String title;

    public Metadata(String url,String title){
	this.url=url;
	this.title=title;
    }

    public void setURL(String s){url=s;}
    
    /**null if none*/
    public String getURL(){return url;}
    
    public void setTitle(String s){title=s;}
    
    /**null if none*/
    public String getTitle(){return title;}

    public String toString(){
	return "url=" + ((url != null) ? url : "") + " title=" + ((title != null) ? title : "");
    }
    
}
