Building Dazboard
=================

The build process is managed by maven
Make sure it is installed (e.g. 'sudo apt-get install naven2' under Ubuntu)

To build Dazboard, try:
$ mvn package
from the dazboard directory

