/*   FILE: Metadata.java
 *   DATE OF CREATION:   Mon Dec 01 10:12:36 2003
 *   AUTHOR :            Emmanuel Pietriga (emmanuel@claribole.net)
 *   MODIF:              Emmanuel Pietriga (emmanuel.pietriga@inria.fr)
 *   Copyright (c) Emmanuel Pietriga, 2003. All Rights Reserved
 *   Copyright (c) INRIA, 2010. All Rights Reserved
 *   Licensed under the GNU LGPL. For full terms see the file COPYING.
 *
 * $Id$  
 */

package fr.inria.zvtm.svg;

/** Metadata associated with SVG graphical elements (title, URL, ...).
 * Attached to glyphs generated by SVGReader.
 * Use Glyph.getOwner() to retrieve this information.
 */

public class Metadata {

    String url;
    String title;
    String closestAncestorGroupClass;
    String closestGroupID;

    public Metadata(String url, String title, String cagid, String cagc){
        this.url=url;
        this.title=title;
        this.closestGroupID = cagid;
        this.closestAncestorGroupClass = cagc;
    }

    /** Set a URL for this part of the SVG document tree. */
    public void setURL(String s){url=s;}
    
    /** Get URL associated with this part of the SVG document tree.
     *@return null if none specified.
     */
    public String getURL(){return url;}
    
    /** Get Title associated with this part of the SVG document tree.
     *@return null if none specified.
     */
    public void setTitle(String s){title=s;}
    
    /** Get Title associated with this part of the SVG document tree.
     *@return null if none specified.
     */
    public String getTitle(){return title;}

    public void setClosestAncestorGroupClass(String s){closestAncestorGroupClass = s;}
    
    /**
     *@return null if none
     */
    public String getClosestAncestorGroupClass(){return closestAncestorGroupClass;}

    public void setClosestAncestorGroupID(String s){closestGroupID = s;}
    
    /**
     *@return null if none
     */
    public String getClosestAncestorGroupID(){return closestGroupID;}

    public String toString(){
	    return "url=" + ((url != null) ? url : "") + " title=" + ((title != null) ? title : "") + " group ID=" + ((closestGroupID != null) ? closestGroupID : "");
    }
    
}
