/*   FILE: ZGRApplet.java
 *   DATE OF CREATION:   Fri May 09 09:52:34 2003
 *   AUTHOR :            Emmanuel Pietriga (emmanuel@w3.org)
 *   MODIF:              Emmanuel Pietriga (emmanuel.pietriga@inria.fr)
 *   Copyright (c) Emmanuel Pietriga, 2002. All Rights Reserved
 *   Licensed under the GNU LGPL. For full terms see the file COPYING.
 */ 

package net.claribole.zgrviewer;

import java.awt.*;
import java.util.Vector;

import javax.swing.JApplet;
import javax.swing.JPanel;

import net.claribole.zvtm.engine.Location;

import org.w3c.dom.Document;

import com.xerox.VTM.engine.*;
import com.xerox.VTM.svg.SVGReader;


public class ZGRApplet extends JApplet {

    static final int DEFAULT_VIEW_WIDTH = 640;
    static final int DEFAULT_VIEW_HEIGHT = 480;
    static final String WIDTH_APPLET_PARAM = "width";
    static final String HEIGHT_APPLET_PARAM = "height";
    static final String SVG_FILE_URL_PARAM = "svgURL";

    VirtualSpaceManager vsm;
    static final String mainSpace = "graphSpace";
    VirtualSpace mSpace;
    View mainView;
    static final String mainViewName = "gvView";
    JPanel mViewPanel;
    Camera mainCamera;
    int appletWindowWidth = DEFAULT_VIEW_WIDTH;
    int appletWindowHeight = DEFAULT_VIEW_HEIGHT;

    ZgrAppletEvtHdlr meh;

    public ZGRApplet(){
	getRootPane().putClientProperty("defeatSystemEventQueueCheck", Boolean.TRUE);
    }

    public void init(){
	try {appletWindowWidth = Integer.parseInt(getParameter(WIDTH_APPLET_PARAM));}
	catch(NumberFormatException ex){appletWindowWidth = DEFAULT_VIEW_WIDTH;}
	try {appletWindowHeight = Integer.parseInt(getParameter(HEIGHT_APPLET_PARAM));}
	catch(NumberFormatException ex){appletWindowHeight = DEFAULT_VIEW_HEIGHT;}
	Container cpane = getContentPane();
	cpane.setBackground(Color.WHITE);
	cpane.setLayout(new FlowLayout());

	AppletUtils.initLookAndFeel();
	vsm = new VirtualSpaceManager(true);
	vsm.setMainFont(ConfigManager.defaultFont);
	vsm.setZoomLimit(-90);
	vsm.setMouseInsideGlyphColor(Color.RED);
	mSpace = vsm.addVirtualSpace(mainSpace);
	mainCamera = vsm.addCamera(mainSpace); // camera #0 for main view
	Vector vc1 = new Vector();
	vc1.add(vsm.getVirtualSpace(mainSpace).getCamera(0));

	this.setSize(appletWindowWidth-10, appletWindowHeight-10);
	cpane.setSize(appletWindowWidth, appletWindowHeight);

	


 	mViewPanel = vsm.addPanelView(vc1, ConfigManager.MAIN_TITLE, appletWindowWidth, appletWindowHeight);

	mViewPanel.setPreferredSize(new Dimension(appletWindowWidth-10, appletWindowHeight-60));

	cpane.add(mViewPanel);

	mainView = vsm.getView(ConfigManager.MAIN_TITLE);
	mainView.setBackgroundColor(ConfigManager.backgroundColor);
	meh = new ZgrAppletEvtHdlr(this);
	mainView.setEventHandler(meh);

	setVisible(true);
	validate();

	final SwingWorker worker = new SwingWorker(){
		public Object construct(){
		    loadSVG();
		    return null; 
		}
	    };
	worker.start();
    }

    void loadSVG(){
	try {
	    String svgFileURL = getParameter(SVG_FILE_URL_PARAM);
	    Document svgDoc = AppletUtils.parse(svgFileURL, false);
	    if (svgDoc != null){
		SVGReader.load(svgDoc, vsm, ZGRApplet.mainSpace, true);
 		getGlobalView();
	    }
	    else {
		System.err.println("An error occured while loading file " + svgFileURL);
	    }
	}
	catch (Exception ex){ex.printStackTrace();}
    }

    void getGlobalView(){
	vsm.getGlobalView(mSpace.getCamera(0),ConfigManager.ANIM_MOVE_LENGTH);
    }


    /**
     * Use this method to get the ZVTM view as JPanel that can be embedded in your JApplet
     */
    public JPanel getPanel(){
	return mViewPanel;
    }

    /**
     *load the SVG file generated by GraphViz from a java.lang.String representing URI (an applet might not allow the URI to point to a server different from the one where the applet comes from)
     */
    public void loadSVG(String uri){
	try {
	    Document svgDoc=AppletUtils.parse(uri,false);
	    SVGReader.load(svgDoc,vsm,mainSpace);
	    //font=vsm.getMainFont();
	    //getGlobalView();
// 	    if (previousLocations.size()==1){previousLocations.removeElementAt(0);} //do not remember camera's initial location (before global view)
	}
	catch (Exception ex){
	    System.err.println(Messages.loadError+uri);
	}
    }

}
