/*   FILE: Metadata.java
 *   DATE OF CREATION:   Mon Dec 01 10:12:36 2003
 *   AUTHOR :            Emmanuel Pietriga (emmanuel@claribole.net)
 *   MODIF:              Emmanuel Pietriga (emmanuel.pietriga@inria.fr)
 *   Copyright (c) Emmanuel Pietriga, 2003. All Rights Reserved
 *   Copyright (c) INRIA, 2010. All Rights Reserved
 *   Licensed under the GNU LGPL. For full terms see the file COPYING.
 *
 * $Id$  
 */

package fr.inria.zvtm.svg;

/**metadata information attached to SVG graphical elements (title, URL, ...) - attached to glyphs generated by SVGReader (use Glyph.getOwner() to retrieve this information)*/

public class Metadata {

    String url;
    String title;
    String closestAncestorGroupClass;
    String closestGroupID;

    public Metadata(String url, String title, String cagid, String cagc){
        this.url=url;
        this.title=title;
        this.closestGroupID = cagid;
        this.closestAncestorGroupClass = cagc;
    }

    public void setURL(String s){url=s;}
    
    /**null if none*/
    public String getURL(){return url;}
    
    public void setTitle(String s){title=s;}
    
    /**null if none*/
    public String getTitle(){return title;}

    public void setClosestAncestorGroupClass(String s){closestAncestorGroupClass = s;}
    
    /**null if none*/
    public String getClosestAncestorGroupClass(){return closestAncestorGroupClass;}

    public void setClosestAncestorGroupID(String s){closestGroupID = s;}
    
    /**null if none*/
    public String getClosestAncestorGroupID(){return closestGroupID;}

    public String toString(){
	return "url=" + ((url != null) ? url : "") + " title=" + ((title != null) ? title : "") + " group ID=" + ((closestGroupID != null) ? closestGroupID : "");
    }
    
}
